export const SUBSCRIPTION_UPDATE_ADDRESS_REQUEST =
  'SUBSCRIPTION_UPDATE_ADDRESS_REQUEST'
export const SUBSCRIPTION_UPDATE_ADDRESS_SUCCESS =
  'SUBSCRIPTION_UPDATE_ADDRESS_SUCCESS'
export const SUBSCRIPTION_UPDATE_ADDRESS_FAIL =
  'SUBSCRIPTION_UPDATE_ADDRESS_FAIL'

export const SUBSCRIPTION_UPDATE_PREFERENCES_REQUEST =
  'SUBSCRIPTION_UPDATE_PREFERENCES_REQUEST'
export const SUBSCRIPTION_UPDATE_PREFERENCES_SUCCESS =
  'SUBSCRIPTION_UPDATE_PREFERENCES_SUCCESS'
export const SUBSCRIPTION_UPDATE_PREFERENCES_FAIL =
  'SUBSCRIPTION_UPDATE_PREFERENCES_FAIL'
export const SUBSCRIPTION_UPDATE_PREFERENCES_CLEAR =
  'SUBSCRIPTION_UPDATE_PREFERENCES_CLEAR'

export const SUBSCRIPTION_CANCEL_REQUEST = 'SUBSCRIPTION_CANCEL_REQUEST'
export const SUBSCRIPTION_CANCEL_SUCCESS = 'SUBSCRIPTION_CANCEL_SUCCESS'
export const SUBSCRIPTION_CANCEL_FAIL = 'SUBSCRIPTION_CANCEL_FAIL'

export const SUBSCRIPTION_LIST_MY_REQUEST = 'SUBSCRIPTION_LIST_MY_REQUEST'
export const SUBSCRIPTION_LIST_MY_SUCCESS = 'SUBSCRIPTION_LIST_MY_SUCCESS'
export const SUBSCRIPTION_LIST_MY_FAIL = 'SUBSCRIPTION_LIST_MY_FAIL'
export const SUBSCRIPTION_LIST_MY_RESET = 'SUBSCRIPTION_LIST_MY_RESET'
